name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug - show working directory
        run: pwd

      - name: Debug - list root files
        run: ls -al

      - name: Debug - list docker-image2 folder
        run: ls -al ./docker-image2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker-image2
          file: ./docker-image2/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hello-world:latest

      - name: Confirm push success
        run: echo "Docker image pushed to Docker Hub as ${{ secrets.DOCKER_USERNAME }}/hello-world:latest"
